import type { PrismaClient } from "@prisma/client";

export async function exportUserData(prisma: PrismaClient, userId: number) {
  const accountFilter = { userId };
  const viaAccount = { account: { userId } };

  const [
    user,
    accounts,
    transactions,
    categories,
    budgets,
    holdings,
    holdingLots,
    instruments,
    incomeEvents,
    liabilities,
    propertyCashFlows,
    propertySales,
    positionTransfers,
    corporateActions,
    taxWrapperWithdrawals,
    ikzeContributions,
    taxLossCarryforwards,
    taxReportSnapshots,
    taxChecklistItems,
    documentAttachments,
    importPresets,
    categorizationRules,
    assetValuations,
    couponSchedules,
    bankConnections,
    accountSyncSettings,
    auditLogs,
    importBatches,
    importRows,
    instrumentValuations,
  ] = await Promise.all([
    prisma.user.findUnique({
      where: { id: userId },
      select: { id: true, email: true, username: true, createdAt: true },
    }),
    prisma.account.findMany({ where: accountFilter }),
    prisma.transaction.findMany({ where: viaAccount, include: { splits: true } }),
    prisma.category.findMany({ where: accountFilter }),
    prisma.budget.findMany({ where: accountFilter }),
    prisma.holding.findMany({ where: viaAccount }),
    prisma.holdingLot.findMany({ where: { holding: viaAccount } }),
    prisma.instrument.findMany({
      where: { holdings: { some: viaAccount } },
    }),
    prisma.incomeEvent.findMany({ where: accountFilter }),
    prisma.liability.findMany({ where: accountFilter }),
    prisma.propertyCashFlow.findMany({ where: accountFilter }),
    prisma.propertySale.findMany({ where: accountFilter }),
    prisma.positionTransfer.findMany({ where: accountFilter }),
    prisma.corporateAction.findMany({ where: accountFilter }),
    prisma.taxWrapperWithdrawal.findMany({ where: accountFilter }),
    prisma.ikzeContribution.findMany({ where: accountFilter }),
    prisma.taxLossCarryforward.findMany({ where: accountFilter }),
    prisma.taxReportSnapshot.findMany({ where: accountFilter }),
    prisma.taxChecklistItem.findMany({ where: accountFilter }),
    prisma.documentAttachment.findMany({ where: accountFilter }),
    prisma.importPreset.findMany({ where: accountFilter }),
    prisma.categorizationRule.findMany({ where: accountFilter }),
    prisma.assetValuation.findMany({ where: accountFilter }),
    prisma.couponSchedule.findMany({ where: accountFilter }),
    prisma.bankConnection.findMany({ where: accountFilter }),
    prisma.accountSyncSetting.findMany({ where: viaAccount }),
    prisma.auditLog.findMany({ where: accountFilter, orderBy: { createdAt: "desc" }, take: 5000 }),
    prisma.importBatch.findMany({ where: viaAccount }),
    prisma.importRow.findMany({ where: { batch: viaAccount } }),
    prisma.instrumentValuation.findMany({
      where: { instrument: { holdings: { some: viaAccount } } },
    }),
  ]);

  return {
    exportedAt: new Date().toISOString(),
    formatVersion: 2,
    user,
    accounts,
    transactions,
    categories,
    budgets,
    holdings,
    holdingLots,
    instruments,
    instrumentValuations,
    incomeEvents,
    liabilities,
    propertyCashFlows,
    propertySales,
    positionTransfers,
    corporateActions,
    taxWrapperWithdrawals,
    ikzeContributions,
    taxLossCarryforwards,
    taxReportSnapshots,
    taxChecklistItems,
    documentAttachments,
    importPresets,
    categorizationRules,
    assetValuations,
    couponSchedules,
    bankConnections,
    accountSyncSettings,
    auditLogs,
    importBatches,
    importRows,
  };
}
